name: Deploy to EC2

on:
   push:
      branches: ['main']  

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v4
      - name: install node-js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - name: check node version
        run: node -v
      - name: install dependencies
        run: npm install --frozen-lockfile
      - name: Build App
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout Code
        uses: actions/checkout@v4
      - name: install node-js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - name: check node version
        run: node -v
      - name: install dependencies
        run: npm install --frozen-lockfile
      - name: Build App
        run: npm run build  

